// packages/wc/src/components/list/list.ts
import { type TemplateResult, html, nothing } from "lit";
import { property, state } from "lit/decorators.js";
import { classMap } from "lit/directives/class-map.js";
import { DSElement } from "../../base/ds-element.js";
import { define } from "../../registry/define.js";
import { emitEvent } from "../../events/emit.js";

export type ListSelectionMode = "single" | "multiple" | "none";
export type ListOrientation = "vertical" | "horizontal";
export type ListSize = "default" | "compact" | "spacious";

/**
 * List root component for collection display.
 *
 * @element ds-list
 *
 * @slot - ListItem elements
 *
 * @fires ds-selection-change - When selection changes
 *
 * @cssprop --ds-list-gap - Gap between items
 */
export class DsList extends DSElement {
  static override styles = [];

  /**
   * Selection mode.
   */
  @property({ type: String, attribute: "selection-mode", reflect: true })
  selectionMode: ListSelectionMode = "single";

  /**
   * List orientation.
   */
  @property({ type: String, reflect: true })
  orientation: ListOrientation = "vertical";

  /**
   * Size variant.
   */
  @property({ type: String, reflect: true })
  size: ListSize = "default";

  /**
   * Show border around list.
   */
  @property({ type: Boolean, reflect: true })
  bordered = false;

  /**
   * Accessible label.
   */
  @property({ type: String })
  label = "List";

  @state()
  private selectedItems: Set<string> = new Set();

  handleItemSelect(itemId: string): void {
    if (this.selectionMode === "none") return;

    if (this.selectionMode === "single") {
      this.selectedItems.clear();
      this.selectedItems.add(itemId);
    } else {
      if (this.selectedItems.has(itemId)) {
        this.selectedItems.delete(itemId);
      } else {
        this.selectedItems.add(itemId);
      }
    }

    emitEvent(this, "selection-change", {
      detail: { selectedItems: Array.from(this.selectedItems) },
    });

    this.requestUpdate();
  }

  isItemSelected(itemId: string): boolean {
    return this.selectedItems.has(itemId);
  }

  override render(): TemplateResult {
    const classes = {
      "ds-list": true,
    };

    return html`
      <ul
        class=${classMap(classes)}
        role="listbox"
        aria-label=${this.label}
        aria-multiselectable=${this.selectionMode === "multiple" ? "true" : nothing}
        aria-orientation=${this.orientation}
        data-size=${this.size !== "default" ? this.size : nothing}
        data-orientation=${this.orientation !== "vertical" ? this.orientation : nothing}
        ?data-bordered=${this.bordered}
      >
        <slot></slot>
      </ul>
    `;
  }
}

// Register the component
define("ds-list", DsList);

// TypeScript declaration for HTML
declare global {
  interface HTMLElementTagNameMap {
    "ds-list": DsList;
  }
}

// packages/react/src/components/list/list.tsx
"use client";

import { forwardRef, createElement, useEffect, useRef, type HTMLAttributes, type ReactNode } from "react";
import "@ds/wc";

export type ListSelectionMode = "single" | "multiple" | "none";
export type ListOrientation = "vertical" | "horizontal";
export type ListSize = "default" | "compact" | "spacious";

export interface ListRootProps extends HTMLAttributes<HTMLElement> {
  /**
   * Selection mode.
   * @default "single"
   */
  selectionMode?: ListSelectionMode;

  /**
   * List orientation.
   * @default "vertical"
   */
  orientation?: ListOrientation;

  /**
   * Size variant.
   * @default "default"
   */
  size?: ListSize;

  /**
   * Show border around list.
   * @default false
   */
  bordered?: boolean;

  /**
   * Accessible label.
   * @default "List"
   */
  label?: string;

  /**
   * Callback when selection changes.
   */
  onSelectionChange?: (selectedItems: string[]) => void;

  /**
   * List content (ListItem elements).
   */
  children?: ReactNode;
}

/**
 * List root component for collection display.
 */
export const ListRoot = forwardRef<HTMLElement, ListRootProps>(function ListRoot(
  {
    selectionMode = "single",
    orientation = "vertical",
    size = "default",
    bordered = false,
    label = "List",
    onSelectionChange,
    children,
    className,
    ...props
  },
  forwardedRef
) {
  const internalRef = useRef<HTMLElement>(null);

  // Sync forwarded ref
  useEffect(() => {
    if (typeof forwardedRef === "function") {
      forwardedRef(internalRef.current);
    } else if (forwardedRef) {
      (forwardedRef as React.MutableRefObject<HTMLElement | null>).current = internalRef.current;
    }
  }, [forwardedRef]);

  // Set up event listeners
  useEffect(() => {
    const element = internalRef.current;
    if (!element) return;

    const handleSelectionChange = (e: Event) => {
      const event = e as CustomEvent<{ selectedItems: string[] }>;
      onSelectionChange?.(event.detail.selectedItems);
    };

    element.addEventListener("ds:selection-change", handleSelectionChange);
    return () => element.removeEventListener("ds:selection-change", handleSelectionChange);
  }, [onSelectionChange]);

  return createElement(
    "ds-list",
    {
      ref: internalRef,
      "selection-mode": selectionMode,
      orientation,
      size,
      bordered: bordered || undefined,
      label,
      class: className,
      ...props,
    },
    children
  );
});
