// apps/demo-wc/src/pages/data-display.ts
import { LitElement, html } from 'lit';
import { customElement } from 'lit/decorators.js';
import { dataDisplaySectionContent, mockUsers, mockProducts, formatPrice } from '@hypoth-ui/demo-shared';

// Import WC components (bundled exports)
import '@hypoth-ui/wc/data-display';

/**
 * Data Display page component showcasing data presentation components
 * Uses Light DOM so global CSS styles apply
 */
@customElement('demo-page-data-display')
export class DemoPageDataDisplay extends LitElement {
  // Use Light DOM so global CSS applies
  protected override createRenderRoot() {
    return this;
  }

  render() {
    return html`
      <nav class="breadcrumb" aria-label="Breadcrumb">
        <a href="#dashboard">Dashboard</a>
        <span class="breadcrumb-separator">/</span>
        <span class="breadcrumb-current" aria-current="page">Data Display</span>
      </nav>
      <div class="page-header">
        <h2 class="page-title">${dataDisplaySectionContent.title}</h2>
        <p class="page-description">${dataDisplaySectionContent.description}</p>
      </div>

      <!-- Table Showcase -->
      <div class="showcase-card">
        <h3 class="showcase-title">Table</h3>
        <p class="showcase-description">
          A structured data table with headers and rows.
        </p>
        <div class="showcase-demo">
          <ds-table>
            <ds-table-header>
              <ds-table-row>
                <ds-table-head>Name</ds-table-head>
                <ds-table-head>Email</ds-table-head>
                <ds-table-head>Role</ds-table-head>
                <ds-table-head>Status</ds-table-head>
              </ds-table-row>
            </ds-table-header>
            <ds-table-body>
              ${mockUsers.slice(0, 5).map(
                (user) => html`
                  <ds-table-row>
                    <ds-table-cell>${user.name}</ds-table-cell>
                    <ds-table-cell>${user.email}</ds-table-cell>
                    <ds-table-cell>${user.role}</ds-table-cell>
                    <ds-table-cell>
                      <ds-badge variant=${user.status === 'active' ? 'success' : user.status === 'pending' ? 'warning' : 'secondary'}>
                        ${user.status}
                      </ds-badge>
                    </ds-table-cell>
                  </ds-table-row>
                `
              )}
            </ds-table-body>
          </ds-table>
        </div>
      </div>

      <!-- Card Showcase -->
      <div class="showcase-card">
        <h3 class="showcase-title">Card</h3>
        <p class="showcase-description">
          A container for grouping related content.
        </p>
        <div class="showcase-demo">
          <div class="cards-grid">
            ${mockProducts.slice(0, 3).map(
              (product) => html`
                <ds-card>
                  <ds-card-header>
                    <div class="card-header-content">${product.name}</div>
                    <div class="card-category">${product.category}</div>
                  </ds-card-header>
                  <ds-card-content>
                    <p class="card-description">${product.description}</p>
                    <div class="card-footer">
                      <span class="price">${formatPrice(product.price)}</span>
                      <ds-badge variant=${product.inStock ? 'success' : 'secondary'}>
                        ${product.inStock ? 'In Stock' : 'Out of Stock'}
                      </ds-badge>
                    </div>
                  </ds-card-content>
                </ds-card>
              `
            )}
          </div>
        </div>
      </div>

      <!-- Avatar Showcase -->
      <div class="showcase-card">
        <h3 class="showcase-title">Avatar</h3>
        <p class="showcase-description">
          A visual representation of a user or entity.
        </p>
        <div class="showcase-demo">
          <div class="avatar-row">
            <ds-avatar size="sm" name="John Doe"></ds-avatar>
            <ds-avatar size="md" name="Jane Smith"></ds-avatar>
            <ds-avatar size="lg" name="Bob Wilson"></ds-avatar>
            <ds-avatar size="lg" name="Alice Johnson" status="active"></ds-avatar>
          </div>
        </div>
      </div>

      <!-- Badge Showcase -->
      <div class="showcase-card">
        <h3 class="showcase-title">Badge</h3>
        <p class="showcase-description">
          A small label for status or count indicators.
        </p>
        <div class="showcase-demo">
          <div class="badge-row">
            <ds-badge>Default</ds-badge>
            <ds-badge variant="secondary">Secondary</ds-badge>
            <ds-badge variant="success">Success</ds-badge>
            <ds-badge variant="warning">Warning</ds-badge>
            <ds-badge variant="destructive">Error</ds-badge>
          </div>
        </div>
      </div>

      <!-- Tag Showcase -->
      <div class="showcase-card">
        <h3 class="showcase-title">Tag</h3>
        <p class="showcase-description">
          A compact element for labeling and categorization.
        </p>
        <div class="showcase-demo">
          <div class="tag-row">
            <ds-tag>React</ds-tag>
            <ds-tag variant="secondary">TypeScript</ds-tag>
            <ds-tag variant="success">Active</ds-tag>
            <ds-tag variant="warning">Pending</ds-tag>
            <ds-tag removable>Removable</ds-tag>
          </div>
        </div>
      </div>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'demo-page-data-display': DemoPageDataDisplay;
  }
}

// apps/demo-react/app/data-display/page.tsx
'use client';

import { Card, Avatar, Badge, Tag, Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@hypoth-ui/react/client';
import { dataDisplaySectionContent, mockUsers, mockProducts, formatPrice } from '@hypoth-ui/demo-shared';
import { SidebarNav } from '../../components/sidebar-nav';
import { AppShell } from '../../components/app-shell';
import { ThemeToggle } from '../../components/theme-toggle';

export default function DataDisplayPage() {
  return (
    <AppShell
      sidebar={<SidebarNav />}
      header={
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', width: '100%' }}>
          <h1 style={{ fontSize: '18px', fontWeight: 600 }}>Demo - React</h1>
          <ThemeToggle />
        </div>
      }
    >
      <nav className="breadcrumb" aria-label="Breadcrumb">
        <a href="/">Dashboard</a>
        <span className="breadcrumb-separator">/</span>
        <span className="breadcrumb-current" aria-current="page">Data Display</span>
      </nav>
      <div className="page-header">
        <h2 className="page-title">{dataDisplaySectionContent.title}</h2>
        <p className="page-description">{dataDisplaySectionContent.description}</p>
      </div>

      {/* Table Showcase */}
      <div className="showcase-card">
        <h3 className="showcase-title">Table</h3>
        <p className="showcase-description">
          A structured data table with headers and rows.
        </p>
        <div className="showcase-demo">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Name</TableHead>
                <TableHead>Email</TableHead>
                <TableHead>Role</TableHead>
                <TableHead>Status</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {mockUsers.slice(0, 5).map((user) => (
                <TableRow key={user.id}>
                  <TableCell>{user.name}</TableCell>
                  <TableCell>{user.email}</TableCell>
                  <TableCell>{user.role}</TableCell>
                  <TableCell>
                    <Badge variant={user.status === 'active' ? 'success' : user.status === 'pending' ? 'warning' : 'secondary'}>
                      {user.status}
                    </Badge>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>
      </div>

      {/* Card Showcase */}
      <div className="showcase-card">
        <h3 className="showcase-title">Card</h3>
        <p className="showcase-description">
          A container for grouping related content.
        </p>
        <div className="showcase-demo">
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', gap: '16px' }}>
            {mockProducts.slice(0, 3).map((product) => (
              <Card.Root key={product.id}>
                <Card.Header>
                  <div style={{ fontWeight: 600 }}>{product.name}</div>
                  <div style={{ fontSize: '14px', color: 'var(--color-muted)' }}>{product.category}</div>
                </Card.Header>
                <Card.Content>
                  <p style={{ fontSize: '14px', color: 'var(--color-muted)', marginBottom: '8px' }}>
                    {product.description}
                  </p>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <span style={{ fontWeight: 600, fontSize: '18px' }}>{formatPrice(product.price)}</span>
                    <Badge variant={product.inStock ? 'success' : 'secondary'}>
                      {product.inStock ? 'In Stock' : 'Out of Stock'}
                    </Badge>
                  </div>
                </Card.Content>
              </Card.Root>
            ))}
          </div>
        </div>
      </div>

      {/* Avatar Showcase */}
      <div className="showcase-card">
        <h3 className="showcase-title">Avatar</h3>
        <p className="showcase-description">
          A visual representation of a user or entity.
        </p>
        <div className="showcase-demo">
          <div style={{ display: 'flex', gap: '16px', alignItems: 'center', flexWrap: 'wrap' }}>
            <Avatar size="sm" name="John Doe" />
            <Avatar size="md" name="Jane Smith" />
            <Avatar size="lg" name="Bob Wilson" />
            <Avatar size="lg" name="Alice Johnson" status="online" />
          </div>
        </div>
      </div>

      {/* Badge Showcase */}
      <div className="showcase-card">
        <h3 className="showcase-title">Badge</h3>
        <p className="showcase-description">
          A small label for status or count indicators.
        </p>
        <div className="showcase-demo">
          <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
            <Badge>Default</Badge>
            <Badge variant="secondary">Secondary</Badge>
            <Badge variant="success">Success</Badge>
            <Badge variant="warning">Warning</Badge>
            <Badge variant="error">Error</Badge>
          </div>
        </div>
      </div>

      {/* Tag Showcase */}
      <div className="showcase-card">
        <h3 className="showcase-title">Tag</h3>
        <p className="showcase-description">
          A compact element for labeling and categorization.
        </p>
        <div className="showcase-demo">
          <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
            <Tag>React</Tag>
            <Tag variant="secondary">TypeScript</Tag>
            <Tag variant="success">Active</Tag>
            <Tag variant="warning">Pending</Tag>
            <Tag removable onRemove={() => {}}>Removable</Tag>
          </div>
        </div>
      </div>
    </AppShell>
  );
}
