// packages/react/src/components/tree/tree.tsx
"use client";

import { forwardRef, createElement, useEffect, useRef, type HTMLAttributes, type ReactNode } from "react";
import "@ds/wc";

export type TreeSelectionMode = "single" | "multiple" | "none";
export type TreeSize = "default" | "compact";

export interface TreeRootProps extends HTMLAttributes<HTMLElement> {
  /**
   * Selection mode.
   * @default "single"
   */
  selectionMode?: TreeSelectionMode;

  /**
   * Size variant.
   * @default "default"
   */
  size?: TreeSize;

  /**
   * Show connecting lines.
   * @default false
   */
  lines?: boolean;

  /**
   * Accessible label.
   * @default "Tree"
   */
  label?: string;

  /**
   * Callback when selection changes.
   */
  onSelectionChange?: (selectedItems: string[]) => void;

  /**
   * Tree content (TreeItem elements).
   */
  children?: ReactNode;
}

/**
 * Tree root component for hierarchical data display.
 */
export const TreeRoot = forwardRef<HTMLElement, TreeRootProps>(function TreeRoot(
  {
    selectionMode = "single",
    size = "default",
    lines = false,
    label = "Tree",
    onSelectionChange,
    children,
    className,
    ...props
  },
  forwardedRef
) {
  const internalRef = useRef<HTMLElement>(null);

  // Sync forwarded ref
  useEffect(() => {
    if (typeof forwardedRef === "function") {
      forwardedRef(internalRef.current);
    } else if (forwardedRef) {
      (forwardedRef as React.MutableRefObject<HTMLElement | null>).current = internalRef.current;
    }
  }, [forwardedRef]);

  // Set up event listeners
  useEffect(() => {
    const element = internalRef.current;
    if (!element) return;

    const handleSelectionChange = (e: Event) => {
      const event = e as CustomEvent<{ selectedItems: string[] }>;
      onSelectionChange?.(event.detail.selectedItems);
    };

    element.addEventListener("ds:selection-change", handleSelectionChange);
    return () => element.removeEventListener("ds:selection-change", handleSelectionChange);
  }, [onSelectionChange]);

  return createElement(
    "ds-tree",
    {
      ref: internalRef,
      "selection-mode": selectionMode,
      size,
      lines: lines || undefined,
      label,
      class: className,
      ...props,
    },
    children
  );
});

// packages/wc/src/components/tree/tree.ts
import { type TemplateResult, html, nothing } from "lit";
import { property, state } from "lit/decorators.js";
import { classMap } from "lit/directives/class-map.js";
import { DSElement } from "../../base/ds-element.js";
import { define } from "../../registry/define.js";
import { emitEvent } from "../../events/emit.js";

export type TreeSelectionMode = "single" | "multiple" | "none";
export type TreeSize = "default" | "compact";

/**
 * Tree root component for hierarchical data display.
 *
 * @element ds-tree
 *
 * @slot - TreeItem elements
 *
 * @fires ds-selection-change - When selection changes
 *
 * @cssprop --ds-tree-indent - Indentation for nested items
 */
export class DsTree extends DSElement {
  static override styles = [];

  /**
   * Selection mode.
   */
  @property({ type: String, attribute: "selection-mode", reflect: true })
  selectionMode: TreeSelectionMode = "single";

  /**
   * Size variant.
   */
  @property({ type: String, reflect: true })
  size: TreeSize = "default";

  /**
   * Show connecting lines.
   */
  @property({ type: Boolean, reflect: true })
  lines = false;

  /**
   * Accessible label.
   */
  @property({ type: String })
  label = "Tree";

  @state()
  private selectedItems: Set<string> = new Set();

  handleItemSelect(itemId: string): void {
    if (this.selectionMode === "none") return;

    if (this.selectionMode === "single") {
      this.selectedItems.clear();
      this.selectedItems.add(itemId);
    } else {
      if (this.selectedItems.has(itemId)) {
        this.selectedItems.delete(itemId);
      } else {
        this.selectedItems.add(itemId);
      }
    }

    emitEvent(this, "selection-change", {
      detail: { selectedItems: Array.from(this.selectedItems) },
    });

    this.requestUpdate();
  }

  isItemSelected(itemId: string): boolean {
    return this.selectedItems.has(itemId);
  }

  override render(): TemplateResult {
    const classes = {
      "ds-tree": true,
    };

    return html`
      <ul
        class=${classMap(classes)}
        role="tree"
        aria-label=${this.label}
        aria-multiselectable=${this.selectionMode === "multiple" ? "true" : nothing}
        data-size=${this.size !== "default" ? this.size : nothing}
        ?data-lines=${this.lines}
      >
        <slot></slot>
      </ul>
    `;
  }
}

// Register the component
define("ds-tree", DsTree);

// TypeScript declaration for HTML
declare global {
  interface HTMLElementTagNameMap {
    "ds-tree": DsTree;
  }
}
