// packages/wc/src/components/input/input.ts
import { html } from "lit";
import { property } from "lit/decorators.js";
import { LightElement } from "../../base/light-element.js";
import { define } from "../../registry/define.js";

export type InputType = "text" | "email" | "password" | "number" | "tel" | "url" | "search";
export type InputSize = "sm" | "md" | "lg";

/**
 * A text input field component.
 *
 * @element ds-input
 * @fires input - Fired when the input value changes
 * @fires change - Fired when the input value is committed
 */
export class DsInput extends LightElement {
  /** Input type */
  @property({ type: String, reflect: true })
  type: InputType = "text";

  /** Input size */
  @property({ type: String, reflect: true })
  size: InputSize = "md";

  /** Input name */
  @property({ type: String, reflect: true })
  name = "";

  /** Input value */
  @property({ type: String })
  value = "";

  /** Placeholder text */
  @property({ type: String })
  placeholder = "";

  /** Disabled state */
  @property({ type: Boolean, reflect: true })
  disabled = false;

  /** Read-only state */
  @property({ type: Boolean, reflect: true })
  readonly = false;

  /** Required state */
  @property({ type: Boolean, reflect: true })
  required = false;

  /** Error state */
  @property({ type: Boolean, reflect: true })
  error = false;

  /** Minimum length */
  @property({ type: Number })
  minlength?: number;

  /** Maximum length */
  @property({ type: Number })
  maxlength?: number;

  /** Pattern for validation */
  @property({ type: String })
  pattern?: string;

  private handleInput(event: Event) {
    const input = event.target as HTMLInputElement;
    this.value = input.value;
    this.dispatchEvent(
      new CustomEvent("input", {
        detail: { value: this.value },
        bubbles: true,
        composed: true,
      })
    );
  }

  private handleChange(event: Event) {
    const input = event.target as HTMLInputElement;
    this.value = input.value;
    this.dispatchEvent(
      new CustomEvent("change", {
        detail: { value: this.value },
        bubbles: true,
        composed: true,
      })
    );
  }

  override render() {
    return html`
      <div class="ds-input" part="container" data-size=${this.size}>
        <input
          part="input"
          class="ds-input__field"
          type=${this.type}
          name=${this.name}
          .value=${this.value}
          placeholder=${this.placeholder}
          ?disabled=${this.disabled}
          ?readonly=${this.readonly}
          ?required=${this.required}
          ?aria-invalid=${this.error}
          minlength=${this.minlength ?? ""}
          maxlength=${this.maxlength ?? ""}
          pattern=${this.pattern ?? ""}
          @input=${this.handleInput}
          @change=${this.handleChange}
        />
      </div>
    `;
  }
}

define("ds-input", DsInput);

declare global {
  interface HTMLElementTagNameMap {
    "ds-input": DsInput;
  }
}

// packages/react/src/components/input.tsx
import type React from "react";
import { type InputHTMLAttributes, createElement, forwardRef, useEffect, useRef } from "react";

export type InputType = "text" | "email" | "password" | "number" | "tel" | "url" | "search";
export type InputSize = "sm" | "md" | "lg";

export interface InputProps
  extends Omit<InputHTMLAttributes<HTMLInputElement>, "size" | "onChange" | "onInput"> {
  /** Input type */
  type?: InputType;
  /** Input size */
  size?: InputSize;
  /** Error state */
  error?: boolean;
  /** Change handler - fires when input loses focus with changed value */
  onChange?: (value: string, event: Event) => void;
  /** Value change handler - fires on every keystroke */
  onValueChange?: (value: string, event: Event) => void;
}

/**
 * React wrapper for ds-input Web Component.
 * Provides type-safe props and event handling.
 */
export const Input = forwardRef<HTMLElement, InputProps>((props, forwardedRef) => {
  const {
    type = "text",
    size = "md",
    name,
    value,
    placeholder,
    disabled = false,
    readOnly = false,
    required = false,
    error = false,
    minLength,
    maxLength,
    pattern,
    onChange,
    onValueChange,
    className,
    ...rest
  } = props;

  const internalRef = useRef<HTMLElement>(null);

  // Merge refs
  useEffect(() => {
    if (typeof forwardedRef === "function") {
      forwardedRef(internalRef.current);
    } else if (forwardedRef) {
      (forwardedRef as React.MutableRefObject<HTMLElement | null>).current = internalRef.current;
    }
  }, [forwardedRef]);

  // Handle input events
  useEffect(() => {
    const element = internalRef.current;
    if (!element) return;

    const handleInputEvent = (event: Event) => {
      const customEvent = event as CustomEvent<{ value: string }>;
      onValueChange?.(customEvent.detail.value, event);
    };

    const handleChangeEvent = (event: Event) => {
      const customEvent = event as CustomEvent<{ value: string }>;
      onChange?.(customEvent.detail.value, event);
    };

    if (onValueChange) {
      element.addEventListener("input", handleInputEvent);
    }
    if (onChange) {
      element.addEventListener("change", handleChangeEvent);
    }

    return () => {
      if (onValueChange) {
        element.removeEventListener("input", handleInputEvent);
      }
      if (onChange) {
        element.removeEventListener("change", handleChangeEvent);
      }
    };
  }, [onValueChange, onChange]);

  return createElement("ds-input", {
    ref: internalRef,
    type,
    size,
    name,
    value,
    placeholder,
    disabled: disabled || undefined,
    readonly: readOnly || undefined,
    required: required || undefined,
    error: error || undefined,
    minlength: minLength,
    maxlength: maxLength,
    pattern,
    class: className,
    ...rest,
  });
});

Input.displayName = "Input";
