// apps/demo-wc/src/pages/forms.ts
import { LitElement, html } from 'lit';
import { customElement, state } from 'lit/decorators.js';
import { formsSectionContent } from '@hypoth-ui/demo-shared';

// Import WC components (bundled exports)
import '@hypoth-ui/wc/form-controls';

/**
 * Forms page component showcasing form input components
 * Uses Light DOM so global CSS styles apply
 */
@customElement('demo-page-forms')
export class DemoPageForms extends LitElement {
  @state()
  private inputValue = '';

  @state()
  private textareaValue = '';

  @state()
  private switchChecked = false;

  @state()
  private checkboxChecked = false;

  // Use Light DOM so global CSS applies
  protected override createRenderRoot() {
    return this;
  }

  render() {
    return html`
      <nav class="breadcrumb" aria-label="Breadcrumb">
        <a href="#dashboard">Dashboard</a>
        <span class="breadcrumb-separator">/</span>
        <span class="breadcrumb-current" aria-current="page">Forms</span>
      </nav>
      <div class="page-header">
        <h2 class="page-title">${formsSectionContent.title}</h2>
        <p class="page-description">${formsSectionContent.description}</p>
      </div>

      <!-- Input Showcase -->
      <div class="showcase-card">
        <h3 class="showcase-title">Input</h3>
        <p class="showcase-description">
          A text input field for collecting user data.
        </p>
        <div class="showcase-demo">
          <div class="form-group">
            <div class="form-field">
              <label for="default-input">Default Input</label>
              <ds-input
                id="default-input"
                placeholder="Enter text..."
                .value=${this.inputValue}
                @ds:change=${(e: CustomEvent) => { this.inputValue = e.detail.value; }}
              ></ds-input>
            </div>
            <div class="form-field">
              <label for="disabled-input">Disabled Input</label>
              <ds-input id="disabled-input" placeholder="Disabled" disabled></ds-input>
            </div>
          </div>
        </div>
      </div>

      <!-- Textarea Showcase -->
      <div class="showcase-card">
        <h3 class="showcase-title">Textarea</h3>
        <p class="showcase-description">
          A multi-line text input for longer content.
        </p>
        <div class="showcase-demo">
          <div class="form-group">
            <div class="form-field">
              <label for="textarea">Message</label>
              <ds-textarea
                id="textarea"
                placeholder="Enter your message..."
                .value=${this.textareaValue}
                rows="4"
                @ds:change=${(e: CustomEvent) => { this.textareaValue = e.detail.value; }}
              ></ds-textarea>
            </div>
          </div>
        </div>
      </div>

      <!-- Checkbox Showcase -->
      <div class="showcase-card">
        <h3 class="showcase-title">Checkbox</h3>
        <p class="showcase-description">
          A toggle for boolean options.
        </p>
        <div class="showcase-demo">
          <div class="checkbox-group">
            <ds-checkbox
              ?checked=${this.checkboxChecked}
              @ds:change=${(e: CustomEvent) => { this.checkboxChecked = e.detail.checked; }}
            >
              Accept terms and conditions
            </ds-checkbox>
            <ds-checkbox disabled>Disabled checkbox</ds-checkbox>
            <ds-checkbox checked>Pre-checked option</ds-checkbox>
          </div>
        </div>
      </div>

      <!-- Radio Group Showcase -->
      <div class="showcase-card">
        <h3 class="showcase-title">Radio Group</h3>
        <p class="showcase-description">
          A group of mutually exclusive options.
        </p>
        <div class="showcase-demo">
          <ds-radio-group value="option1">
            <ds-radio value="option1">Option 1</ds-radio>
            <ds-radio value="option2">Option 2</ds-radio>
            <ds-radio value="option3">Option 3</ds-radio>
          </ds-radio-group>
        </div>
      </div>

      <!-- Switch Showcase -->
      <div class="showcase-card">
        <h3 class="showcase-title">Switch</h3>
        <p class="showcase-description">
          A toggle switch for on/off states.
        </p>
        <div class="showcase-demo">
          <div class="switch-group">
            <ds-switch
              ?checked=${this.switchChecked}
              @ds:change=${(e: CustomEvent) => { this.switchChecked = e.detail.checked; }}
            >
              Enable notifications
            </ds-switch>
            <ds-switch disabled>Disabled switch</ds-switch>
            <ds-switch checked>Pre-enabled option</ds-switch>
          </div>
        </div>
      </div>

      <!-- Select Showcase -->
      <div class="showcase-card">
        <h3 class="showcase-title">Select</h3>
        <p class="showcase-description">
          A dropdown selection component.
        </p>
        <div class="showcase-demo">
          <div style="max-width: 300px;">
            <div class="form-field">
              <label>Choose an option</label>
              <ds-select>
                <ds-select-trigger>
                  <span slot="placeholder">Select an option</span>
                </ds-select-trigger>
                <ds-select-content>
                  <ds-select-option value="option1">Option 1</ds-select-option>
                  <ds-select-option value="option2">Option 2</ds-select-option>
                  <ds-select-option value="option3">Option 3</ds-select-option>
                </ds-select-content>
              </ds-select>
            </div>
          </div>
        </div>
      </div>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'demo-page-forms': DemoPageForms;
  }
}

// apps/demo-react/app/forms/page.tsx
'use client';

import { useState } from 'react';
import { Input, Textarea, Switch, Checkbox, RadioGroup, Radio, Select } from '@hypoth-ui/react/client';
import { formsSectionContent } from '@hypoth-ui/demo-shared';
import { SidebarNav } from '../../components/sidebar-nav';
import { AppShell } from '../../components/app-shell';
import { ThemeToggle } from '../../components/theme-toggle';

export default function FormsPage() {
  const [inputValue, setInputValue] = useState('');
  const [textareaValue, setTextareaValue] = useState('');
  const [switchChecked, setSwitchChecked] = useState(false);
  const [checkboxChecked, setCheckboxChecked] = useState(false);
  const [radioValue, setRadioValue] = useState('option1');

  return (
    <AppShell
      sidebar={<SidebarNav />}
      header={
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', width: '100%' }}>
          <h1 style={{ fontSize: '18px', fontWeight: 600 }}>Demo - React</h1>
          <ThemeToggle />
        </div>
      }
    >
      <nav className="breadcrumb" aria-label="Breadcrumb">
        <a href="/">Dashboard</a>
        <span className="breadcrumb-separator">/</span>
        <span className="breadcrumb-current" aria-current="page">Forms</span>
      </nav>
      <div className="page-header">
        <h2 className="page-title">{formsSectionContent.title}</h2>
        <p className="page-description">{formsSectionContent.description}</p>
      </div>

      {/* Input Showcase */}
      <div className="showcase-card">
        <h3 className="showcase-title">Input</h3>
        <p className="showcase-description">
          A text input field for collecting user data.
        </p>
        <div className="showcase-demo">
          <div style={{ display: 'flex', flexDirection: 'column', gap: '16px', maxWidth: '400px' }}>
            <div>
              <label htmlFor="default-input" style={{ display: 'block', marginBottom: '4px', fontSize: '14px', fontWeight: 500 }}>
                Default Input
              </label>
              <Input
                id="default-input"
                placeholder="Enter text..."
                value={inputValue}
                onChange={(value) => setInputValue(value)}
              />
            </div>
            <div>
              <label htmlFor="disabled-input" style={{ display: 'block', marginBottom: '4px', fontSize: '14px', fontWeight: 500 }}>
                Disabled Input
              </label>
              <Input id="disabled-input" placeholder="Disabled" disabled />
            </div>
          </div>
        </div>
      </div>

      {/* Textarea Showcase */}
      <div className="showcase-card">
        <h3 className="showcase-title">Textarea</h3>
        <p className="showcase-description">
          A multi-line text input for longer content.
        </p>
        <div className="showcase-demo">
          <div style={{ maxWidth: '400px' }}>
            <label htmlFor="textarea" style={{ display: 'block', marginBottom: '4px', fontSize: '14px', fontWeight: 500 }}>
              Message
            </label>
            <Textarea
              id="textarea"
              placeholder="Enter your message..."
              value={textareaValue}
              onChange={(value) => setTextareaValue(value)}
              rows={4}
            />
          </div>
        </div>
      </div>

      {/* Checkbox Showcase */}
      <div className="showcase-card">
        <h3 className="showcase-title">Checkbox</h3>
        <p className="showcase-description">
          A toggle for boolean options.
        </p>
        <div className="showcase-demo">
          <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
            <Checkbox
              checked={checkboxChecked}
              onChange={(checked) => setCheckboxChecked(checked)}
            >
              Accept terms and conditions
            </Checkbox>
            <Checkbox disabled>Disabled checkbox</Checkbox>
            <Checkbox defaultChecked>Pre-checked option</Checkbox>
          </div>
        </div>
      </div>

      {/* Radio Group Showcase */}
      <div className="showcase-card">
        <h3 className="showcase-title">Radio Group</h3>
        <p className="showcase-description">
          A group of mutually exclusive options.
        </p>
        <div className="showcase-demo">
          <RadioGroup
            value={radioValue}
            onChange={(value) => setRadioValue(value)}
          >
            <Radio value="option1">Option 1</Radio>
            <Radio value="option2">Option 2</Radio>
            <Radio value="option3">Option 3</Radio>
          </RadioGroup>
        </div>
      </div>

      {/* Switch Showcase */}
      <div className="showcase-card">
        <h3 className="showcase-title">Switch</h3>
        <p className="showcase-description">
          A toggle switch for on/off states.
        </p>
        <div className="showcase-demo">
          <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
            <Switch
              checked={switchChecked}
              onChange={setSwitchChecked}
            >
              Enable notifications
            </Switch>
            <Switch disabled>Disabled switch</Switch>
            <Switch defaultChecked>Pre-enabled option</Switch>
          </div>
        </div>
      </div>

      {/* Select Showcase */}
      <div className="showcase-card">
        <h3 className="showcase-title">Select</h3>
        <p className="showcase-description">
          A dropdown selection component.
        </p>
        <div className="showcase-demo">
          <div style={{ maxWidth: '300px' }}>
            <label htmlFor="select" style={{ display: 'block', marginBottom: '4px', fontSize: '14px', fontWeight: 500 }}>
              Choose an option
            </label>
            <Select.Root>
              <Select.Trigger>
                <Select.Value placeholder="Select an option" />
              </Select.Trigger>
              <Select.Content>
                <Select.Option value="option1">Option 1</Select.Option>
                <Select.Option value="option2">Option 2</Select.Option>
                <Select.Option value="option3">Option 3</Select.Option>
              </Select.Content>
            </Select.Root>
          </div>
        </div>
      </div>
    </AppShell>
  );
}
