// packages/wc/src/components/aspect-ratio/aspect-ratio.ts
/**
 * AspectRatio component - maintains consistent width-to-height ratio.
 *
 * @element ds-aspect-ratio
 *
 * @slot - Default slot for content to maintain aspect ratio
 *
 * @example
 * ```html
 * <ds-aspect-ratio ratio="16/9">
 *   <img src="image.jpg" alt="..." />
 * </ds-aspect-ratio>
 * <ds-aspect-ratio ratio="4/3">
 *   <video src="video.mp4"></video>
 * </ds-aspect-ratio>
 * ```
 */

import { html } from "lit";
import { property } from "lit/decorators.js";
import { DSElement } from "../../base/ds-element.js";
import { define } from "../../registry/define.js";

export class DsAspectRatio extends DSElement {
  /**
   * Aspect ratio as width/height (e.g., "16/9", "4/3", "1/1").
   * Can also be a number (e.g., 1.777 for 16:9).
   */
  @property({ reflect: true })
  ratio = "1/1";

  override updated(): void {
    this.updateCssVariable();
  }

  override connectedCallback(): void {
    super.connectedCallback();
    this.updateCssVariable();
  }

  private updateCssVariable(): void {
    const ratioValue = this.parseRatio(this.ratio);
    this.style.setProperty("--ds-aspect-ratio", String(ratioValue));
  }

  private parseRatio(ratio: string): number {
    // Handle fraction format like "16/9"
    if (ratio.includes("/")) {
      const parts = ratio.split("/").map(Number);
      const width = parts[0];
      const height = parts[1];
      if (
        width !== undefined &&
        height !== undefined &&
        !Number.isNaN(width) &&
        !Number.isNaN(height) &&
        height !== 0
      ) {
        return width / height;
      }
    }
    // Handle decimal format
    const parsed = Number.parseFloat(ratio);
    return Number.isNaN(parsed) ? 1 : parsed;
  }

  override render() {
    return html`<slot></slot>`;
  }
}

define("ds-aspect-ratio", DsAspectRatio);

declare global {
  interface HTMLElementTagNameMap {
    "ds-aspect-ratio": DsAspectRatio;
  }
}

// packages/react/src/components/aspect-ratio/index.tsx
/**
 * AspectRatio component React wrapper.
 *
 * @example
 * ```tsx
 * import { AspectRatio } from "@hypoth-ui/react";
 *
 * <AspectRatio ratio="16/9">
 *   <img src="image.jpg" alt="..." />
 * </AspectRatio>
 * ```
 */

import { type HTMLAttributes, type ReactNode, createElement, forwardRef } from "react";

// ============================================================================
// Types
// ============================================================================

export interface AspectRatioProps extends HTMLAttributes<HTMLElement> {
  /** Content to maintain aspect ratio */
  children?: ReactNode;
  /**
   * Aspect ratio as width/height (e.g., "16/9", "4/3", "1/1").
   * Can also be a number (e.g., 1.777 for 16:9).
   */
  ratio?: string | number;
}

// ============================================================================
// Component
// ============================================================================

/**
 * AspectRatio component - maintains consistent width-to-height ratio.
 */
export const AspectRatio = forwardRef<HTMLElement, AspectRatioProps>(function AspectRatio(
  { children, className, ratio = "1/1", ...props },
  ref
) {
  const ratioString = typeof ratio === "number" ? String(ratio) : ratio;

  return createElement(
    "ds-aspect-ratio",
    { ref, class: className, ratio: ratioString, ...props },
    children
  );
});

AspectRatio.displayName = "AspectRatio";
