// packages/cli/templates/skeleton/wc/skeleton.ts
import { type TemplateResult, html, nothing } from "lit";
import { property } from "lit/decorators.js";
import { classMap } from "lit/directives/class-map.js";
import { styleMap } from "lit/directives/style-map.js";
import { DSElement } from "../../base/ds-element.js";
import { define } from "../../registry/define.js";

export type SkeletonVariant = "text" | "circular" | "rectangular" | "rounded";
export type SkeletonSize = "xs" | "sm" | "md" | "lg" | "xl";
export type SkeletonWidth = "full" | "3/4" | "1/2" | "1/4";
export type SkeletonAnimation = "wave" | "pulse" | "none";

/**
 * Skeleton loading placeholder component.
 *
 * @element ds-skeleton
 *
 * @cssprop --ds-skeleton-bg - Background color
 * @cssprop --ds-skeleton-highlight - Shimmer highlight color
 * @cssprop --ds-skeleton-radius - Border radius
 */
export class DsSkeleton extends DSElement {
  static override styles = [];

  /**
   * Shape variant.
   */
  @property({ type: String, reflect: true })
  variant: SkeletonVariant = "text";

  /**
   * Size preset for height.
   */
  @property({ type: String, reflect: true })
  size?: SkeletonSize;

  /**
   * Width preset.
   */
  @property({ type: String, reflect: true })
  width?: SkeletonWidth;

  /**
   * Custom width (CSS value).
   */
  @property({ type: String, attribute: "custom-width" })
  customWidth = "";

  /**
   * Custom height (CSS value).
   */
  @property({ type: String, attribute: "custom-height" })
  customHeight = "";

  /**
   * Animation type.
   */
  @property({ type: String, reflect: true })
  animation: SkeletonAnimation = "wave";

  /**
   * Accessible label for screen readers.
   */
  @property({ type: String })
  label = "Loading...";

  override render(): TemplateResult {
    const classes = {
      "ds-skeleton": true,
    };

    const styles: Record<string, string> = {};
    if (this.customWidth) {
      styles.width = this.customWidth;
    }
    if (this.customHeight) {
      styles.height = this.customHeight;
    }

    return html`
      <div
        class=${classMap(classes)}
        role="status"
        aria-busy="true"
        aria-label=${this.label}
        data-variant=${this.variant}
        data-size=${this.size || nothing}
        data-width=${!this.customWidth && this.width ? this.width : nothing}
        data-animation=${this.animation}
        ?data-no-animation=${this.animation === "none"}
        style=${Object.keys(styles).length > 0 ? styleMap(styles) : nothing}
      >
        <span class="ds-visually-hidden">${this.label}</span>
      </div>
    `;
  }
}

// Register the component
define("ds-skeleton", DsSkeleton);

// TypeScript declaration for HTML
declare global {
  interface HTMLElementTagNameMap {
    "ds-skeleton": DsSkeleton;
  }
}

// packages/cli/templates/skeleton/index.tsx
"use client";

import { type HTMLAttributes, createElement, forwardRef } from "react";
import "@ds/wc";
import {
  type ResponsiveProp,
  generateResponsiveDataAttr,
  isResponsiveObject,
  resolveResponsiveValue,
} from "@/lib/primitives/responsive.js";

export type SkeletonVariant = "text" | "circular" | "rectangular" | "rounded";
export type SkeletonSize = "xs" | "sm" | "md" | "lg" | "xl";
export type SkeletonWidth = "full" | "3/4" | "1/2" | "1/4";
export type SkeletonAnimation = "wave" | "pulse" | "none";

export interface SkeletonProps extends Omit<HTMLAttributes<HTMLElement>, "children"> {
  /**
   * Shape variant.
   * @default "text"
   */
  variant?: SkeletonVariant;

  /**
   * Size preset for height - supports responsive object syntax.
   * @example
   * ```tsx
   * // Single value
   * <Skeleton size="md" />
   *
   * // Responsive
   * <Skeleton size={{ base: "sm", md: "lg" }} />
   * ```
   */
  size?: ResponsiveProp<SkeletonSize>;

  /**
   * Width preset.
   */
  width?: SkeletonWidth;

  /**
   * Custom width (CSS value).
   */
  customWidth?: string;

  /**
   * Custom height (CSS value).
   */
  customHeight?: string;

  /**
   * Animation type.
   * @default "wave"
   */
  animation?: SkeletonAnimation;

  /**
   * Accessible label for screen readers.
   * @default "Loading..."
   */
  label?: string;
}

/**
 * Skeleton loading placeholder component for content that is loading.
 *
 * @example
 * ```tsx
 * // Text skeleton
 * <Skeleton variant="text" width="3/4" />
 *
 * // Circular avatar skeleton
 * <Skeleton variant="circular" customWidth="40px" customHeight="40px" />
 *
 * // Card skeleton layout
 * <div className="space-y-2">
 *   <Skeleton variant="rectangular" customHeight="200px" />
 *   <Skeleton variant="text" width="1/2" />
 *   <Skeleton variant="text" />
 *   <Skeleton variant="text" width="3/4" />
 * </div>
 * ```
 */
export const Skeleton = forwardRef<HTMLElement, SkeletonProps>(function Skeleton(
  {
    variant = "text",
    size,
    width,
    customWidth,
    customHeight,
    animation = "wave",
    label = "Loading...",
    className,
    ...props
  },
  ref
) {
  // Resolve responsive size - use base value for the WC attribute
  const resolvedSize = size ? resolveResponsiveValue(size, "md") : undefined;
  const isResponsive = size ? isResponsiveObject(size) : false;
  const responsiveSizeAttr = isResponsive && size ? generateResponsiveDataAttr(size) : undefined;

  return createElement("ds-skeleton", {
    ref,
    variant,
    size: resolvedSize,
    width,
    "custom-width": customWidth,
    "custom-height": customHeight,
    animation,
    label,
    class: className,
    // Add responsive data attribute for CSS targeting
    "data-size-responsive": responsiveSizeAttr,
    ...props,
  });
});

// TypeScript declaration for JSX
declare global {
  namespace JSX {
    interface IntrinsicElements {
      "ds-skeleton": SkeletonProps & {
        ref?: React.Ref<HTMLElement>;
        "custom-width"?: string;
        "custom-height"?: string;
      };
    }
  }
}
